[package]
name = "tier3-projects"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
chrono.workspace = true
rand.workspace = true

[dev-dependencies]
tempfile = "3.8"
